name: Run Playwright Script

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'Ringzor09/adverlink'
          path: 'adverlink'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: adverlink
        run: |
          npm install
          npx playwright install  # Ensure Playwright dependencies are installed

      - name: Run Playwright script
        working-directory: adverlink
        run: node playwright/test.js
